{
 "title": "Real-time water quality monitoring with global positioning - GUI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "GNSS/INS data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  latitude AS \"Latitude\", longitude AS \"Longitude\",altitude AS \"Altitude\", velocityx AS \"Velocity X\",velocityy AS \"Velocity Y\",velocityz AS \"Velocity Z\", yaw AS \"Yaw\", pitch AS \"Pitch\", roll AS \"Roll\"\nFROM Vectors2\nORDER BY time asc"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  battery AS \"Battery\"\nFROM Sensors2\nORDER BY time asc"
    }
   ]
  },
  {
   "title": "Multiparameter Sonde",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature AS \"Temperature\", pressure AS \"Pressure\", depth AS \"Depth\", depthw AS \"Level, Depth to Water\", surface AS \"Level, Surface Elevation\", conductivitya AS \"Actual Conductivity\", conductivitys AS \"Specific Conductivity\", resistivity AS \"Resistivity\", salinity AS \"Salinity\", solidsd AS \"Total Dissolver Solids\", waterd AS \"Density of Water\", pressureb AS \"Barometric Pressure\", ph AS \"pH\", phmv AS \"pH mV\", orp AS \"ORP\", concetrationo AS \"Disolved Oxygen Concetration\", saturationo AS \"Dissolved Oxygen % Saturation\", pressureo AS \"Oxygen Partial Pressure\", voltage AS \"External Voltage\", battery AS \"Battery Capacity\"\nFROM Sensors2\nORDER BY time asc"
    }
   ]
  }
 ]
}